name: Deploy-to-Beta-VULTR

on:
  push:
    branches:
      - 'main'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare
      id: prep
      shell: bash
      run: |
        GIT_BRANCH=master
        GIT_COMMIT=$(git rev-parse --short HEAD)
        DOCKER_TAG_COMMIT="$GIT_BRANCH.$GIT_COMMIT"
        DOCKER_TAGS="$DOCKER_IMAGE:$DOCKER_TAG_COMMIT,$DOCKER_IMAGE:latest"
        
        echo ::set-output name=git_branch::${GIT_BRANCH}
        echo ::set-output name=git_commit::${GIT_COMMIT}
        echo ::set-output name=docker_tag_commit::${DOCKER_TAG_COMMIT}
        echo ::set-output name=docker_tags::${DOCKER_TAGS}
    - name: copy docker compose file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 108.61.203.197
        username: abogaard
        port: 22
        key: ${{secrets.VULTR_SSH_KEY}}
        source: "geeseband-app/"
        target: "/home/abogaard"
    - name: Update environment variables and restart docker containers on vultr
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: 108.61.203.197
        key: ${{secrets.VULTR_SSH_KEY}}
        username: abogaard
        script: |
          cd /home/abogaard
          npm install
          npm run build
          sudo mv /home/abogaard/build/* /var/www/html
